// Code generated by generate-data. DO NOT EDIT.

package data

func loadEt() map[string]struct{} {
	return map[string]struct{}{
		"aga":    {},
		"ei":     {},
		"et":     {},
		"ja":     {},
		"jah":    {},
		"kas":    {},
		"kui":    {},
		"kõik":   {},
		"ma":     {},
		"me":     {},
		"mida":   {},
		"midagi": {},
		"mind":   {},
		"minu":   {},
		"mis":    {},
		"mu":     {},
		"mul":    {},
		"mulle":  {},
		"nad":    {},
		"nii":    {},
		"oled":   {},
		"olen":   {},
		"oli":    {},
		"oma":    {},
		"on":     {},
		"pole":   {},
		"sa":     {},
		"seda":   {},
		"see":    {},
		"selle":  {},
		"siin":   {},
		"siis":   {},
		"ta":     {},
		"te":     {},
		"ära":    {},
	}
}
