// Code generated by generate-data. DO NOT EDIT.

package data

func loadSt() map[string]struct{} {
	return map[string]struct{}{
		"a":     {},
		"ba":    {},
		"bane":  {},
		"bona":  {},
		"e":     {},
		"ea":    {},
		"eaba":  {},
		"empa":  {},
		"ena":   {},
		"ha":    {},
		"hae":   {},
		"hape":  {},
		"ho":    {},
		"hore":  {},
		"ka":    {},
		"ke":    {},
		"la":    {},
		"le":    {},
		"li":    {},
		"me":    {},
		"mo":    {},
		"moo":   {},
		"ne":    {},
		"o":     {},
		"oa":    {},
		"re":    {},
		"sa":    {},
		"se":    {},
		"tloha": {},
		"tsa":   {},
		"tse":   {},
	}
}
